# Generated by Django 3.2.6 on 2021-08-09 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_devices_group_notify_target_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_notify',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a73574a2-f8e1-11eb-984c-08d40c3b3e1e')),
        ),
    ]
