# Generated by Django 3.2.6 on 2021-08-09 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210809_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_notify',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6ed6d2ec-f8e8-11eb-8041-08d40c3b3e1e')),
        ),
    ]
