# Generated by Django 3.2.6 on 2021-08-09 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210809_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c00029cc-f8e8-11eb-8ebd-08d40c3b3e1e')),
        ),
    ]
