# Generated by Django 3.2.6 on 2021-08-09 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20210809_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('57dd95d2-f901-11eb-8a02-08d40c3b3e1e')),
        ),
    ]
