# Generated by Django 3.2.6 on 2021-08-10 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_group_notify_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0dd00b9e-f9aa-11eb-8130-08d40c3b3e1e')),
        ),
    ]
