# Generated by Django 3.2.6 on 2021-08-10 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_group_notify_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4eaa2650-f9d2-11eb-b5b9-08d40c3b3e1e')),
        ),
        migrations.AlterField(
            model_name='notify',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notifications.group_notify'),
        ),
    ]
