# Generated by Django 3.2.6 on 2021-08-10 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20210810_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8153f600-fa04-11eb-8563-08d40c3b3e1e')),
        ),
    ]
