# Generated by Django 3.2.6 on 2021-11-09 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_group_notify_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_notify',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8ea85338-4131-11ec-b219-33d9a9f90bc1')),
        ),
    ]
